apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "horizon.web" . }}
  labels:
{{ include "horizon.labels" . | indent 4 }}
data:
  nginx.conf: |+
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /tmp/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '{"remoteAddr": "$remote_addr", "remoteUser": "$remote_user", "timeLocal":
                              "$time_local", "request": "$request", "bodyBytesSent": "$body_bytes_sent", "requestTime": "$request_time",
                              "status": "$status", "requestLength": "$request_length", "httpReferrer":
                              "$http_referer", "httpUserAgent": "$http_user_agent", "upstreamAddr": "$upstream_addr",
                              "upstreamResponseLength": "$upstream_response_length",
                              "upstreamResponseTime": "$upstream_response_time", "upstreamStatus":
                              "$upstream_status"}'

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        server {
            listen {{ .Values.web.port }};
            # gzip config
            gzip on;
            gzip_min_length 1k;
            gzip_comp_level 9;
            gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png;
            gzip_vary on;
            gzip_disable "MSIE [1-6]\.";
            add_header Cache-Control no-store;

            root /usr/share/nginx/html;

            location / {
                # used with browserHistory
                try_files $uri /index.html;
            }
        }
    }